# This workflow will run unit, e2e, and docs tests on PRs targeted against `main`.

name: Has Changesets

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v3
      - name: Decide whether to publish to `next` or `latest`
        id: has-changesets
        run: |
          if (find .changeset -type f -name '*.md' ! -name 'README.md' | grep -q .) ; then
              echo "::set-output name=publish-to::next"
          else
              echo "::set-output name=publish-to::latest"
          fi
      - name: Echo `publish-to`
        run: echo "Publishing to ${{ steps.has-changesets.outputs.publish-to }}"
