# This workflow will run unit, e2e, and docs tests on PRs targeted against `main`.

name: Has Changesets

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v3
      - name: Check if repo has unconsumed changesets
        id: has-changesets
        uses: ./.github/actions/has-changesets
      - name: Echo has-changesets
        run: echo ${{ steps.has-changesets.outputs.has-changesets }}
      - name: Echo where to publish to
        run: echo "Publishing to ${{ steps.publish-target.outputs.target }}"
