name: Publish to latest

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: write # Used to commit to "Version Packages" PR
  pull-requests: write # Used to create "Version Packages" PR
  # Other permissions are defaulted to none

jobs:
  version:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Check if repo has unconsumed changesets
        id: has-changesets
        uses: ./.github/actions/has-changesets
      - name: Create Version Packages PR
        run: echo "mock version packages PR"
